# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:

- script: dir


- task: UiPathPack@2
  inputs:
    versionType: 'AutoVersion'
    projectJsonPath: 'clien-sample\project.json'
    outputType: 'Process'
    orchestratorConnection: 'cloud'
    outputPath: '$(Build.ArtifactStagingDirectory)\Output'

- task: UiPathDeploy@2
  inputs:
    orchestratorConnection: 'cloud'
    packagesPath: '$(Build.ArtifactStagingDirectory)\Output'
    folderName: 'Default'
  
